### ISSUE TITLE
nwt.derh.wdh318efw1 shows incorrect humidity value

### ISSUE THREAD

**Issue by shift-del1** [syssi/xiaomi_airpurifier#87]
All 3 values (current_humidity, humidity and target_humidity) shows the same valuefor New Widetech Internet Dehumidifer (18l), which is the target humidity I set. Can you please check? Thank you.

**Comment by syssi** [comment]
Are you sure about the model name (`nwt.derh.wdh318efw1`) of your device? Could you provide the firmware version of your device?

**Comment by shift-del1** [comment]
Yes, this is the proper model number:
![Screenshot_2020-10-31-14-59-43-986_com android chrome](https://user-images.githubusercontent.com/63366470/97781208-0c41ae80-1b8a-11eb-9438-ffe43abd3043.jpg)
Firmware has been updated to this version right after I bought it:
![Screenshot_2020-10-31-15-00-25-981_com xiaomi smarthome](https://user-images.githubusercontent.com/63366470/97781210-14015300-1b8a-11eb-9521-dd8cbf8a2f04.jpg)
The actual humidity measured in Xiaomi Home app (versus the 50% on the first screenshot from HA):
![Screenshot_2020-10-31-15-00-37-240_com xiaomi smarthome](https://user-images.githubusercontent.com/63366470/97781215-182d7080-1b8a-11eb-810d-cb9ea313f767.jpg)

**Comment by syssi** [comment]
Do you have a linux host and are you able to make some miioclio calls?

```
pip3 install python-miiio
# retrieves the current humidity
miiocli device --ip IP --token TOKEN raw_command get_prop '["humidity"]'
# retrieves the target humidity
miiocli device --ip IP --token TOKEN raw_command get_prop '["auto"]'
```

**Comment by shift-del1** [comment]
Unfortunately I grown up on Windows, I tried to install an Ubuntu VM, but failed to install cíyptography, hence python-miio. Is there any other option for the log?

**Comment by syssi** [comment]
You could try to install `python-miio` on windows, too.

**Comment by shift-del1** [comment]
Installed Debian on VM and could finnaly set up miiocli. Here is the result:

![image](https://user-images.githubusercontent.com/63366470/97811437-ec3de800-1c7a-11eb-92f4-a5f756d50a11.png)

**Comment by syssi** [comment]
Could you provide the current values available via HA and the MiHome app?

**Comment by syssi** [comment]
Please update the custom component to the `develop` branch. The issue should be fixed now.

**Comment by shift-del1** [comment]
![Screenshot_2020-11-01-19-53-11-769_io homeassistant companion android](https://user-images.githubusercontent.com/63366470/97811725-ada92d00-1c7c-11eb-94d2-6369d7196171.jpg)

![Screenshot_2020-11-01-19-53-36-199_com xiaomi smarthome](https://user-images.githubusercontent.com/63366470/97811730-b7329500-1c7c-11eb-915e-31bad464ee4a.jpg)

**Comment by shift-del1** [comment]
Develop branch installed, it looks fine in Developer tools;

![Screenshot_2020-11-01-20-06-03-062_io homeassistant companion android](https://user-images.githubusercontent.com/63366470/97811917-ebf31c00-1c7d-11eb-972e-28e115d972b0.jpg)

Although in Lovelace something is still not ok, but I don't think it is your integration:
![Screenshot_2020-11-01-20-08-33-431_io homeassistant companion android](https://user-images.githubusercontent.com/63366470/97811944-28bf1300-1c7e-11eb-98d0-46135fa91359.jpg)

Thank you for your quick fix.

**Comment by syssi** [comment]
I made another change because `humidity` should contain the target humidity. This is the new mapping:

1. miio property `humidity` is mapped to `current_humidity`
2. miio property `auto` is mapped to `humidity` and `target_humidity`

**Comment by shift-del1** [comment]
Yes, it's perfect now. Thanks again.

![Screenshot_2020-11-01-20-20-27-414_io homeassistant companion android](https://user-images.githubusercontent.com/63366470/97812166-c6671200-1c7f-11eb-9f9a-75978891ba2d.jpg)

**Comment by syssi** [comment]
@shift-del1 Could you help to improve this list of supported devices? https://github.com/syssi/xiaomi_airpurifier#supported-devices

Could you provide the product name, the model no. and some specs about your device model?

**Comment by shift-del1** [comment]
name: NWT (NEW WIDETECH) Internet Dehumidifier
model: nwt.derh.wdh318efw1
model number: WDH318EFW1

description:
Brand: NEW WIDETECH
Model: WDH318EFW1
Voltage: 220V
Frequency: 50Hz
Power: 240W
Rated Dehumidification ( 30℃ RH80%): 18L / D
Nominal Dehumidification ( 20℃ RH60%): 0.4kg / h
Humidity Adjustment: RH40%, RH50%, RH60%
Nosie: 38 db (A)
Water Tank Capacity: 2.7L
Timing: 24 Hours (Only APP)
Application Area: 5-40㎡
Material: ABS Plastic
Color: White
--
Product Weight: 11.3kg
Package Weight: 11.73kg
Product Size: 33.40 x 22.00 x 47.00 cm

Main Features:
● 18L Strong Dehumidification: stable and efficient work efficiency, the dehumidifier machine can absorb up to 18L of water per day from the air, equivalent to 72 bottles of 250ml of mineral water.

● Rapid Dehumidification: fast and powerful dehumidification ability, can reduce the humidity of 18 ㎡ to a comfortable environment after one hour of starting.

● Constant Temperature Dehumidification: the dehumidifier machine utilizes the principle of cold and heat balance, so that the dehumidified air will not be cold, so that the contrast before and after room temperature is kept at ±2 °C.

● 5 Modes & 3 Gear Speed: continuous dehumidification mode, dry clothes function, three comfortable humidity (40%, 50%, 60%), and 3 speeds can be selected to meet the needs of a variety of home environments.

● Built-in Silver Ion Antibacterial Filter: when dehumidifying, the E. coli in the air is removed, and the air of the room of 25 m2 can be taken in 30 minutes

● 38dB (A) Bass Operation: the DC motor is used to adjust the appropriate speed, combined with the vibration and noise reduction design of the compressor, which makes the noise as low as 38dB(A).

● Intelligent Humidity Control: through the Mijia APP, you can realize remote design of multiple modes and control the humidity of your home at any time.

● Energy Saving, Comfortable Dehumidification: energy Saving, Comfortable Dehumidification:
● Patented Heat Sink: the patent-certified heat sink enables energy conversion to be more efficient, reducing energy loss and achieving power savings.

**Comment by shift-del1** [comment]
OFFTOPIC: I have a Mi Air Purifier 2S and 3, Mi Smart Standing Fan 1X, I will add those to your list of supported devices soon.

**Comment by syssi** [comment]
@shift-del1 Some details about the other devices would be nice!
